/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import model.City;
import model.Community;
import model.Doctor;
import model.Hospital;
import model.Patient;
import model.UserLogin;
import static ui.MainJFrame.userLoginList;
import static ui.MainJFrame.commList;
import static ui.MainJFrame.splitPane;
import static ui.MainJFrame.doctorDirectory;
import static ui.MainJFrame.patientDirectory;

/**
 *
 * @author Admin
 */
public class LoginJPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoginJPanel
     */
    
    public LoginJPanel() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        txtUserName = new javax.swing.JTextField();
        txtPass = new javax.swing.JTextField();
        lblUserName = new javax.swing.JLabel();
        lblPass = new javax.swing.JLabel();

        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserNameActionPerformed(evt);
            }
        });

        lblUserName.setText("UserName");

        lblPass.setText("Password");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblUserName)
                    .addComponent(lblPass))
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1)
                    .addComponent(txtUserName, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                    .addComponent(txtPass))
                .addContainerGap(315, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUserName))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPass))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(197, 197, 197))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //conditons to redirect to sys,comm,hos,doc and patient
        //starting with sys:
        if((txtUserName.getText().equals("sysadmin"))&&(txtPass.getText().equals("123"))){
           SysAdminJPanel sysPanel=new SysAdminJPanel();
           MainJFrame.splitPane.setRightComponent(sysPanel);
        
    }
        //check for Patient and then Doctor
        
        for(UserLogin e :userLoginList.getUserLoginList()){
            
            if(txtUserName.getText().equals(e.getUserName())&&txtPass.getText().equals(e.getPass())){
                if(e.getUserType().equals("Patient")){
                    PatientJPanel  patientPanel= new PatientJPanel();
                    //SearchJPanel searchPanel = new SearchJPanel(commList);
                    splitPane.setRightComponent(patientPanel);
                   
                }
                else if(e.getUserType().equals("Doctor")){
                    for(Doctor d:doctorDirectory.getDoctorDirectory()){
                        
                        if(d.getDocID().equals(e.getUid())){
                            
                            System.out.print(d.getDocID());
                            SelectPatientJPanel patientPanel= new SelectPatientJPanel(d);//need to access that particular doctor list here
                            splitPane.setRightComponent(patientPanel);
                            
                        }
                        
                        
                    }
                    
                }
                else if(e.getUserType().equals("Community Admin")){
                    //give access to crud in his/her community
                    for(Community c: commList.getCommList()){
                        if(c.getCommunityName().equals(e.getUserName())){
                            CommunityAdminJPanel communityPanel=new CommunityAdminJPanel(c);//access to list of hospitals 
                            splitPane.setRightComponent(communityPanel);
                            
                        }
                    }
                    
                }
                else if(e.getUserType().equals("Hospital Admin")){
                    for(Community c: commList.getCommList()){
                        for(Hospital h:c.getHospitalDirectory()){
                            if(h.getHospitalName().equals(e.getUserName())){
                            HospitalAdminJPanel hospitalPanel=new HospitalAdminJPanel(h);//access to list of hospitals 
                            splitPane.setRightComponent(hospitalPanel);
                            break;
                            
                        }
                    }
                    
                }
                }
                else{
                    JOptionPane.showMessageDialog(this,"User Type does not exist");
                }
            }
            
        }
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JTextField txtPass;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
